id: I1D8A165E
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-e43b
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 10:15:05.835793+00:00
last_modified: 2023-09-28 10:15:05.835801+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W17033
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW17033
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྭ་སྟོད་བསྡུས་གྲྭ་དང་དེའི་དོགས་བཅོད།
  languages:
  - bo
  author: ཤངས་པ་ཀུན་མཁྱེན་མཆོག་ལྷ་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.9970218009016846
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG16164:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16164
      total_pages: 730
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16164.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9970218009016846
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
